### ISSUE TITLE
4.js is misleading

### ISSUE THREAD

**Issue by brunolemos** [vkurchatkin/typescript-vs-flow#14]
It's not giving errors on flow but the code says it is:

<img width="735" alt="image" src="https://user-images.githubusercontent.com/619186/38166659-e5697984-34fd-11e8-8fbf-e46d0e36b92a.png">

Demo: [Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVxhgGLyQEzgFMBnAOwHIAXMACwEMA3IsEgByIGMBLemVgJ5kq9AB5gocAE5giZAK4BbEqk5wyJGgFU2YALxgAjAG5V6zWAAiiMvrAAmU2o00AMkSg0DAZifmaAErcAOa0XmAALKaoVAIcVtxSXFTc6vqoYGAAPmCxHHBQYDoZ2blxRAVWNiU5eRWF7p41ZfmFQaFUqNFEomzSNFDyZJwpaVSkVAAUjABcCUkjqWQAlGAA3qgAvujjmpOGAAwHy8ZgmLJSUtJAA)

If we change the code to `type Direction = 1 | 2 | 3 | 4`, both flow and typescript will work as expected, and that is actually the recommended syntax for this use case ([ref](https://github.com/Microsoft/TypeScript-Handbook/issues/476#issuecomment-271413194)).

Demo: [Flow](https://flow.org/try/#0C4TwDgpgBAIglgJwgY2HA9gOygXigRigB8oAmYqAZgoBYAoOiADzHQWCgDMBXTVDbMAgBnYAAoAbgC5YiFGiwBKKAG86AXwZDRY-AAY9igNxQA9KagQECNkA) | [TypeScript](https://www.typescriptlang.org/play/index.html#src=type%20Direction%20%3D%201%20%7C%202%20%7C%203%20%7C%204%0D%0A%0D%0Aexport%20function%20test(v%3A%20Direction)%20%7B%0D%0A%7D%0D%0A%0D%0Atest(100)%3B%20%2F%2F%20error)

**Comment by brunolemos** [comment]
If we change the code to:
```
type Direction =
  | 1
  | 2
  | 3
  | 4
;
```

both flow and typescript will work as expected.

**Comment by vkurchatkin** [comment]
See #7

**Comment by brunolemos** [comment]
Plus #6
